db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.url=jdbc:sqlserver://DESKTOP-7015LS2:1433;databaseName=CourseManagement;encrypt=true;trustServerCertificate=true
db.username=course_app
db.password=Course@123456