# ==========================
# SQL Server
# ==========================

db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.url=jdbc:sqlserver://DESKTOP-7015LS2:1433;databaseName=CourseManagement;encrypt=true;trustServerCertificate=true
db.username=course_app
db.password=Course@123456


# ==========================
# Gmail SMTP
# ==========================

mail.host=smtp.gmail.com
mail.port=465

mail.username=bactracnguyen@gmail.com
mail.password=nrpgxjzwmmbbrzvt

mail.auth=true
mail.starttls=false
mail.ssl=true
mail.debug=true

mail.from=bactracnguyen@gmail.com
mail.fromName=Course Management System


